### ISSUE TITLE
DKG takes too long

### ISSUE THREAD

**Issue by yrdsm666** [IBM/TSS#34]
DKG time consumption seems to increase exponentially as the number of nodes increases. DKG time consumption seems to increase exponentially as the number of nodes increases. When the total number of nodes is 20, the DKG time is 2 minutes, and when the number is 25, the time is one hour.

**Comment by yacovm** [comment]
Thanks for your report. 

Which DKG are you using? ECDSA? EDDSA? BLS? 

Are you running this on a single machine? Several? 

Note that the DKG is very CPU intensive, so running it on a single machine may be slow.
