### ISSUE TITLE
go get github.com/IBM/TSS/mpc/binance/ecdsa facing issue.

### ISSUE THREAD

**Issue by ThantZin-develope** [IBM/TSS#5]
When I try to go get the github.com/IBM/TSS/mpc/binance/ecdsa package, the following issue occurs

**_github.com/IBM/TSS/mpc/binance/ecdsa imports
        github.com/bnb-chain/tss-lib/tss imports
        github.com/btcsuite/btcd/btcec: cannot find module providing package github.com/btcsuite/btcd/btcec_**

**Comment by yacovm** [comment]
should be fixed now
