### ISSUE TITLE
Cannot recover the ethereum wallet address from the generated signature!!

### ISSUE THREAD

**Issue by ThantZin-develope** [IBM/TSS#6]
Although, signature is verified successfully within the Libaray. I'ld like to verify inside my SignatureVerifiableContract.sol in which all the required functions for wallet recovery process is implemented. And I tested the signature generated using web3.js . Everything is working as expected. But the signature generated from the ecdsa protocol of this lib is not working. Even when I try to recover with web3.js, it throw exception with the message "invalid point".
Whats wrong?

**Comment by yacovm** [comment]
What is the elliptic curve you're using?
